#!/usr/bin/env python3
"""Generate a single-file build of Melon3D.

    python tools/amalgamate.py [output_dir]     (default: dist/)

Produces melon3d_single.cpp. Drop that file plus include/melon3d.h into any
C or C++ project (compile the .cpp as C++17, link nothing else) and the whole
engine comes along - no build system integration required.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCES = ["collide.cpp", "grid.cpp", "xpbd.cpp", "world.cpp"]


def strip_local_includes(text: str) -> str:
    lines = []
    for line in text.splitlines():
        s = line.strip()
        if s in ('#include "melon3d.h"', '#include "m3d_internal.h"', "#pragma once"):
            continue
        lines.append(line)
    return "\n".join(lines).strip() + "\n"


def main() -> None:
    out_dir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "dist"
    out_dir.mkdir(parents=True, exist_ok=True)

    version = "unknown"
    header = (ROOT / "include" / "melon3d.h").read_text(encoding="utf-8")
    major = minor = patch = "?"
    for line in header.splitlines():
        if line.startswith("#define M3D_VERSION_MAJOR"):
            major = line.split()[-1]
        elif line.startswith("#define M3D_VERSION_MINOR"):
            minor = line.split()[-1]
        elif line.startswith("#define M3D_VERSION_PATCH"):
            patch = line.split()[-1]
    version = f"{major}.{minor}.{patch}"

    parts = [
        f"// melon3d_single.cpp - amalgamated single-file build of Melon3D {version}\n"
        "// Generated by tools/amalgamate.py - do not edit by hand.\n"
        "//\n"
        "// Usage: put this file and melon3d.h in your project, compile this file\n"
        "// as C++17 (e.g. -O3, plus -mavx2 -mfma on x86), include melon3d.h from\n"
        "// C or C++ code. Threads: link with your platform's thread library if\n"
        "// the compiler does not do it automatically (-pthread on Linux).\n"
        "// SPDX-License-Identifier: MIT\n"
        '#include "melon3d.h"\n'
    ]

    internal = (ROOT / "src" / "m3d_internal.h").read_text(encoding="utf-8")
    parts.append("// --- src/m3d_internal.h " + "-" * 50 + "\n" + strip_local_includes(internal))

    for name in SOURCES:
        src = (ROOT / "src" / name).read_text(encoding="utf-8")
        parts.append(f"// --- src/{name} " + "-" * 50 + "\n" + strip_local_includes(src))

    out_file = out_dir / "melon3d_single.cpp"
    out_file.write_text("\n".join(parts), encoding="utf-8", newline="\n")
    print(f"wrote {out_file} ({out_file.stat().st_size // 1024} KiB)")


if __name__ == "__main__":
    main()
